FORMAT: 1A
HOST: https://hepaimusic.com/api
CURRENT VERSION: v2

# 合拍 API

# Group Project

Collaborate with other users in making music

## Own Projects [/user/projects]

List own projects

+ Parameters
    
    + type = `all` (optional, string) ... Type of projects to list. Possible values are `all`, `owner`, `member`, `public`, `private`

+ Model (application/json)

    + Body

            [{
                "id": "529d526282ae474d3100000c",
                "name": "test",
                "description": "",
                "description_html": "",
                "public": true,
                "created_at": "2013-12-03T11:39:14+08:00",
                "updated_at": "2013-12-03T11:39:14+08:00",
                "user": {},
                "members": []

            }, {
                "id": "529d526282ae474d3100900c",
                "name": "test2",
                "description": "",
                "description_html": "",
                "public": true,
                "created_at": "2013-12-03T11:39:14+08:00",
                "updated_at": "2013-12-03T11:39:14+08:00",
                "user": {},
                "members": []
            }]

### List Own Project [GET]

Get list of own projects

+ Response 200

    [Own Projects][]

## Project [/projects{?type}{?per}{?page}]

Project awesomeness

+ Model (application/json)

    + Body

            {
                "id": "1",
                "own": true,
                "name": "测试",
                "description": "测试"
            }

### Creating Project [POST]

Create new project

+ Request (application/json)

        {
            "name": "测试"
            "description": "测试"
        }

+ Response 201 (application/json)

    [Project][]

### List Projects [GET]

List of projects

+ Parameters

    + per = `10` (optional, number) ... number of results per page

    + page = `1` (optional, number) ... current page number

+ Response 200 (application/json)

    [Own Projects][]

### Single Project [/projects/{projectId}]

Existing project

#### Updating Project [PUT]

Update existing project

+ Request (application)

        {
            "name": "不测试了"
        }

+ Response 200

    [Project][]

#### Deleting Project [DELETE]

Delete existing project

+ Response 204
